增加poster图片质量配置
caryyu/jellyfin-plugin-opendouban pull request #42
Opened 2022-06-13 11:12 UTC by cxfksword

默认图有时比较模糊，改为后台可以配置返回更高质量的图片

![](https://fastly.jsdelivr.net/gh/kozalak-robot/assets@main/img/1655118341584Xnip2022-06-13_19-05-12.png)

2022-06-13 13:02 UTC, caryyu commented
@cxfksword 建议在服务端进行处理，根据请求传参来选择图片质量：https://github.com/caryyu/douban-openapi-server/blob/main/provider/httprequest_provider.py#L115

2022-06-13 13:03 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/Configuration/PluginConfiguration.cs
> +        public string PosterQuality { get; set; }
```suggestion
        public string PosterSize { get; set; }
```

2022-06-13 13:05 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/Providers/OddbImageProvider.cs
> +            primary.Img = ImageUtils.GetHighQualityImage(primary.Img, OddbPlugin.Instance?.Configuration.PosterQuality);
为了兼容考虑可以扩展 GetBySidWithOptions 函数，如：`_oddbApiClient.GetBySidWithOptions(sid, options, cancellationToken)`

2022-06-13 13:06 UTC, caryyu requested changes
需要再额外适配一下。

2022-06-13 13:41 UTC, cxfksword commented
好，我先改下服务器端的

2022-06-15 03:59 UTC, cxfksword commented
已修改为从服务器端获取不同大小的图片，你再看下

2022-06-15 06:16 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/Configuration/config.html
> +                        <label class="selectLabel inputLabelUnfocused" for="PosterSize">Poster Image Size</label>
```suggestion
                        <label class="selectLabel inputLabelUnfocused" for="PosterSize">Poster Size</label>

```

2022-06-15 07:05 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +        public async Task<ApiSubject> GetBySidWithOptions(string sid, GetBySidOptions options, CancellationToken cancellationToken = default)
options 使用字典就行了 Dictionary<string, string>

2022-06-15 09:28 UTC, cxfksword commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +        public async Task<ApiSubject> GetBySidWithOptions(string sid, GetBySidOptions options, CancellationToken cancellationToken = default)
已更新，再看下

2022-06-15 10:11 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +            string url = $"{ApiBaseUri}/movies/{sid}?s={posterSize}";
可能换成这种方式更好：https://stackoverflow.com/questions/829080/how-to-build-a-query-string-for-a-url-in-c - 直接使用工具类把所有传入的 parameters 与 URL 连接起来。

2022-06-15 10:12 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +            string url = $"{ApiBaseUri}/movies/{sid}?s={posterSize}";
我想了一下，可能把 options 换成 params 会更直观一些，

2022-06-15 10:39 UTC, cxfksword commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +            string url = $"{ApiBaseUri}/movies/{sid}?s={posterSize}";
这样就需要引入`Microsoft.AspNetCore.WebUtilities` dll了，不知有没影响

2022-06-15 10:41 UTC, cxfksword commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +            string url = $"{ApiBaseUri}/movies/{sid}?s={posterSize}";
params换不了，params是C#的关键词，或者换成parameters？

2022-06-15 10:54 UTC, caryyu commented on Jellyfin.Plugin.OpenDouban/OddbApiClient.cs
> +            string url = $"{ApiBaseUri}/movies/{sid}?s={posterSize}";
OK，那就换成 parameters 吧。

2022-06-15 11:38 UTC, cxfksword commented
已更新，再看下

2022-06-15 11:41 UTC, caryyu commented
@cxfksword 感谢，我先测试一下。

2022-06-16 04:42 UTC, caryyu approved these changes

2022-06-16 04:42 UTC, merged